package main

import (
	"database/sql"
	"strings"
	"testing"
)

// TestReloadFreshCarriesTheSymbolStore is the carry read for the third
// and oldest paid store. symbol_resolutions sat outside the carry list
// for longer than the other two — it is per-source rather than global,
// and it resolves an instrument rather than categorising a payer, so it
// reads less like a "verdict store" than it is. It is bought from the
// same model and regenerated by nothing, so a rebuild that dropped it
// would silently spend that money again.
func TestReloadFreshCarriesTheSymbolStore(t *testing.T) {
	cfg := setupCLITest(t)
	if _, _, code := run(t, "-c", cfg, "init"); code != 0 {
		t.Fatal("init failed")
	}
	if _, _, code := run(t, "-c", cfg, "load", "schwab-test"); code != 0 {
		t.Fatal("load failed")
	}
	goldPath := goldPathFromCfg(cfg)

	db, err := sql.Open("duckdb", goldPath)
	if err != nil {
		t.Fatalf("open gold: %v", err)
	}
	if _, err := db.Exec(`
        INSERT INTO symbol_resolutions (silver_source_id, lookup_kind, lookup_value,
                                        symbol, resolved_at, model_name)
        VALUES ('schwab-test', 'name', 'Example Growth Fund', 'EXGF', 100, 'test-model')`); err != nil {
		t.Fatalf("seed symbol store: %v", err)
	}
	if err := db.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}

	so, se, code := run(t, "-c", cfg, "reload", "-a")
	if code != 0 {
		t.Fatalf("reload -a failed: code=%d stderr=%s", code, se)
	}
	if !strings.Contains(so, "carried 1 symbol verdict(s) across the rebuild") {
		t.Errorf("reload -a did not report the symbol carry-across:\n%s", so)
	}

	ro, err := sql.Open("duckdb", goldPath+"?access_mode=read_only")
	if err != nil {
		t.Fatalf("reopen gold: %v", err)
	}
	defer ro.Close()
	var source, kind, symbol, model string
	if err := ro.QueryRow(`
        SELECT silver_source_id, lookup_kind, symbol, model_name
          FROM symbol_resolutions WHERE lookup_value = 'Example Growth Fund'`).
		Scan(&source, &kind, &symbol, &model); err != nil {
		t.Fatalf("the symbol resolution did not survive the rebuild: %v", err)
	}
	// The source scoping is the whole difference from the other two
	// stores: a resolution carried without it would answer for every
	// source rather than the one it was bought for.
	if source != "schwab-test" || kind != "name" || symbol != "EXGF" {
		t.Errorf("carried resolution = (%q, %q, %q)", source, kind, symbol)
	}
	if model != "test-model" {
		t.Errorf("carried resolution lost its provenance: model=%q", model)
	}
}
